[package]
name = "parse-display-derive"
version = "0.5.3"
authors = ["frozenlib"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/frozenlib/parse-display"
documentation = "https://docs.rs/parse-display/"
keywords = ["derive", "enum", "from_str", "display", "regex"]
categories = ["parsing"]
description = "Procedural macro to implement Display and FromStr using common settings."
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.68", features = ["visit"] }
quote = "1.0.9"
proc-macro2 = "1.0.26"
regex = "1.4.5"
regex-syntax = "0.6.23"
once_cell = "1.7.2"
structmeta = "0.1.4"
