[package]
name = "parse-display-derive"
version = "0.4.0"
authors = ["frozenlib"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/frozenlib/parse-display"
documentation = "https://docs.rs/parse-display/"
keywords = ["derive", "enum", "from_str", "display", "regex"]
categories = ["parsing"]
description = "Procedural macro to implement Display and FromStr using common settings."
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.54", features = ["visit"] }
quote = "1.0.7"
proc-macro2 = "1.0.24"
regex = "1.4.2"
regex-syntax = "0.6.21"
once_cell = "1.4"
