[package]
name = "parse-display-tests"
version = "0.0.0"
authors = ["frozenlib <frozenlib@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
parse-display = { path = "../parse-display" }
trybuild = "1.0.41"
